configs = [
  "../objectives/ce.toml",
  "../objectives/ntxent.toml",
  "../objectives/supcon.toml",
  "../objectives/sincere.toml",
  "../objectives/sigmoid_supcon.toml",
]

[grid]
"run.seed" = [0, 1, 2]
